### ISSUE TITLE
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by SilenceGoo** [robustsam/RobustSAM#8]
Thansk for your great work. I followed commands step by step but got one error. Could guess what cause the problem? Thanks in advacne.

<img width="608" alt="Xshell_60YH70OOPC" src="https://github.com/robustsam/RobustSAM/assets/31915549/1366fe77-0aa0-4f94-a3ad-f28f63468159">

**Comment by robustsam** [comment]
I haven't encountered this problem before, but the [components.py](https://github.com/robustsam/RobustSAM/blob/main/robust_segment_anything/modeling/components.py) file was updated recently. Please try again to check whether the same problem occurs. Thank you.

**Comment by SilenceGoo** [comment]
Thanks for your reply. My setting environment may have problem as I updated the new code but error still. Will do more check.

**Comment by robustsam** [comment]
There is a similar discussion on [https://github.com/pytorch/pytorch/issues/88038](url).  I hope it helps.

**Comment by SilenceGoo** [comment]
Seems different CUDA verison or pytorch version might be the direct cause, will report here after more tests done.

**Comment by SilenceGoo** [comment]
Good news, I tried `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu120` instead of `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` to install bit lower version pkgs to match my CUDA:12.4, and it worked on RTX 4090. 

Few warning info have no problems right?

<img width="712" alt="MobaXterm_U8VQQi2GJ9" src="https://github.com/user-attachments/assets/df6c7126-f674-4a4a-bdad-bc22fe301c88">
